---
# Pick one of the scenarios described in the vm_scenarios dict below
vm_scenario: compact

vm_scenarios:
  compact:
    ceph1:
      template: template-rhel78
      disks:
        scsi1: 20
        scsi2: 20
      groups:
      - mons
      - mgrs
      - osds
      - mdss
      - grafana-server
    ceph2:
      template: template-rhel78
      disks:
        scsi1: 20
        scsi2: 20
      groups:
      - mons
      - mgrs
      - osds
      - mdss
    ceph3:
      template: template-rhel78
      disks:
        scsi1: 20
        scsi2: 20
      groups:
      - mons
      - mgrs
      - osds
  full:
    mon1:
      template: template-rhel78
      groups:
      - mons
      - mgrs
    mon2:
      template: template-rhel78
      groups:
      - mons
      - mgrs
    mon3:
      template: template-rhel78
      groups:
      - mons
      - mgrs
    osd1:
      template: template-rhel78
      groups:
      - osds
    osd2:
      template: template-rhel78
      groups:
      - osds
    osd3:
      template: template-rhel78
      groups:
      - osds
    mds1:
      template: template-rhel78
      groups:
      - mdss
    mds2:
      template: template-rhel78
      groups:
      - mdss
