---
# Pick one of the scenarios described in the vm_scenarios dict below
vm_scenario: compact

# Describes the scenarios you wish to create - should be fairly self explanatory
#
# vm_scenarios:
#  <scenario_name>:
#    <hostname>:
#      template: <The name of the VM template created by the proxmox-templates role>
#      disks: # This dict describes additional disks to be added to the VMs
#      groups: # A list of inventory groups - this is used to build the ceph-ansible inventory file

vm_scenarios:
  compact:
    ceph1:
      template: "{{ vm_default_template }}"
      disks:
        scsi1: 20
        scsi2: 20
      groups:
      - mons
      - mgrs
      - osds
      - mdss
      - grafana-server
      - clients
    ceph2:
      template: "{{ vm_default_template }}"
      disks:
        scsi1: 20
        scsi2: 20
      groups:
      - mons
      - mgrs
      - osds
      - mdss
    ceph3:
      template: "{{ vm_default_template }}"
      disks:
        scsi1: 20
        scsi2: 20
      groups:
      - mons
      - mgrs
      - osds
  full:
    mon1:
      template: "{{ vm_default_template }}"
      groups:
      - mons
      - mgrs
      - grafana-server
      - clients
    mon2:
      template: "{{ vm_default_template }}"
      groups:
      - mons
      - mgrs
    mon3:
      template: "{{ vm_default_template }}"
      groups:
      - mons
      - mgrs
    osd1:
      template: "{{ vm_default_template }}"
      groups:
      - osds
    osd2:
      template: "{{ vm_default_template }}"
      groups:
      - osds
    osd3:
      template: "{{ vm_default_template }}"
      groups:
      - osds
    mds1:
      template: "{{ vm_default_template }}"
      groups:
      - mdss
    mds2:
      template: "{{ vm_default_template }}"
      groups:
      - mdss

# This is for changes to the ansible.cfg file in /usr/share/ceph-ansible
ceph_ansible_cfg_changes:
- regexp: '^log_path = '
  line: 'log_path = /home/{{ ansible_user }}/ansible/ansible.log'

ceph_ansible_group_vars_changes:
- name: osds.yml
  changes:
  - regexp: '^#osd_auto_discovery: false$'
    line: 'osd_auto_discovery: true'
  - regexp: '^#osd_scenario: dummy$'
    line: 'osd_scenario: collocated'
- name: all.yml
  changes:
  - regexp: '^ceph_origin: repository'
    line: 'ceph_origin: distro'
  - regexp: '^#monitor_interface: interface'
    line: 'monitor_interface: eth0'
  - regexp: '^containerized_deployment: False'
    line: 'containerized_deployment: True'
  - regexp: '^#ceph_docker_registry_username:'
    line: !unsafe "ceph_docker_registry_username: \"{{ '{{' }} rhsm_username {{ '}}' }}\""
  - regexp: '^#ceph_docker_registry_password:'
    line: !unsafe "ceph_docker_registry_password: \"{{ '{{' }} rhsm_password {{ '}}' }}\""
  - regexp: '^#dashboard_admin_password:'
    line: !unsafe "dashboard_admin_password: \"{{ '{{' }} ceph_dashboard_admin_password {{ '}}' }}\""
  - regexp: '^#grafana_admin_password:'
    line: !unsafe "grafana_admin_password: \"{{ '{{' }} ceph_grafana_admin_password {{ '}}' }}\""
