---
# Pick one of the scenarios described in the vm_scenarios dict below
vm_scenario: compact

# Describes the scenarios you wish to create - should be fairly self explanatory
#
# vm_scenarios:
#  <scenario_name>:
#    <hostname>:
#      template: <The name of the VM template created by the proxmox-templates role>
#      disks: # A list of dicts describing additional disks to be added to the VMs (scsi1, scsi2 etc follows the proxmox syntax for disks)
#      groups: # A list of inventory groups - this is used to build the ceph-ansible inventory file

vm_name_prefix: "{% if ceph_cluster_name %}{{ ceph_cluster_name }}-{% endif %}"

vm_scenarios:
  compact:
    ceph1:
      template: "{{ vm_default_template }}"
      disks:
      - name: scsi1
        size: 20
      - name: scsi2
        size: 20
      groups:
      - mons
      - mgrs
      - osds
      - mdss
      - grafana-server
      - clients
    ceph2:
      template: "{{ vm_default_template }}"
      disks:
      - name: scsi1
        size: 20
      - name: scsi2
        size: 20
      groups:
      - mons
      - mgrs
      - osds
      - mdss
    ceph3:
      template: "{{ vm_default_template }}"
      disks:
      - name: scsi1
        size: 20
      - name: scsi2
        size: 20
      groups:
      - mons
      - mgrs
      - osds
  full:
    mon1:
      template: "{{ vm_default_template }}"
      groups:
      - mons
      - mgrs
      - grafana-server
      - clients
    mon2:
      template: "{{ vm_default_template }}"
      groups:
      - mons
      - mgrs
    mon3:
      template: "{{ vm_default_template }}"
      groups:
      - mons
      - mgrs
    osd1:
      template: "{{ vm_default_template }}"
      groups:
      - osds
      disks:
      - name: scsi1
        size: 20
      - name: scsi2
        size: 20
    osd2:
      template: "{{ vm_default_template }}"
      groups:
      - osds
      disks:
      - name: scsi1
        size: 20
      - name: scsi2
        size: 20
    osd3:
      template: "{{ vm_default_template }}"
      groups:
      - osds
      disks:
      - name: scsi1
        size: 20
      - name: scsi2
        size: 20
    mds1:
      template: "{{ vm_default_template }}"
      groups:
      - mdss
    mds2:
      template: "{{ vm_default_template }}"
      groups:
      - mdss
