---
# Pick one of the scenarios described in the vm_scenarios dict below
vm_scenario: compact

# Describes the scenarios you wish to create - should be fairly self explanatory
#
# vm_scenarios:
#  <scenario_name>:
#    <hostname>:
#      template: <The name of the VM template created by the proxmox-templates role>
#      disks: # This dict describes additional disks to be added to the VMs
#      groups: # A list of inventory groups - this is used to build the ceph-ansible inventory file

vm_scenarios:
  compact:
    ceph1:
      template: "{{ vm_default_template }}"
      disks:
        scsi1: 20
        scsi2: 20
      groups:
      - mons
      - mgrs
      - osds
      - mdss
      - grafana-server
      - clients
    ceph2:
      template: "{{ vm_default_template }}"
      disks:
        scsi1: 20
        scsi2: 20
      groups:
      - mons
      - mgrs
      - osds
      - mdss
    ceph3:
      template: "{{ vm_default_template }}"
      disks:
        scsi1: 20
        scsi2: 20
      groups:
      - mons
      - mgrs
      - osds
  full:
    mon1:
      template: "{{ vm_default_template }}"
      groups:
      - mons
      - mgrs
      - grafana-server
      - clients
    mon2:
      template: "{{ vm_default_template }}"
      groups:
      - mons
      - mgrs
    mon3:
      template: "{{ vm_default_template }}"
      groups:
      - mons
      - mgrs
    osd1:
      template: "{{ vm_default_template }}"
      groups:
      - osds
    osd2:
      template: "{{ vm_default_template }}"
      groups:
      - osds
    osd3:
      template: "{{ vm_default_template }}"
      groups:
      - osds
    mds1:
      template: "{{ vm_default_template }}"
      groups:
      - mdss
    mds2:
      template: "{{ vm_default_template }}"
      groups:
      - mdss

