---
default_vm_cpu_count: 2
default_vm_memory_mb: 4096
default_vm_onboot: no
default_vm_ssh_user: cloud-user

proxmox_templates:
  template-rhel77:
    image: rhel-server-7.7-update-1-x86_64-kvm.qcow2
    sha_checksum: 7c92debfda5d78d227b53e5b50950b2378c89e1eb5e6db37c00ab06bd3aea7df
    src_dir: "{{ qcow_image_local_source_dir | default('/home/iso') }}"
    rhsm_release: 7.7
  template-rhel78:
    image: rhel-server-7.8-update-3-x86_64-kvm.qcow2
    sha_checksum: 81348efa9c898ca00b144e5242951e08607fa2428c6af048ecde84a060c8d106
    src_dir: "{{ qcow_image_local_source_dir | default('/home/iso') }}"
    rhsm_release: 7.8
  template-rhel81:
    image: rhel-8.1-update-3-x86_64-kvm.qcow2
    sha_checksum: 1e25c46cc4644a2b913f4d5bea3a0a91180f539fb41bcf22ee0ca8a6cd4b8363
    src_dir: "{{ qcow_image_local_source_dir | default('/home/iso') }}"
    rhsm_release: 8.1
  template-rhel82:
    image: rhel-8.2-update-2-x86_64-kvm.qcow2
    sha_checksum: 588167f828001e57688ec4b9b31c11a59d532489f527488ebc89ac5e9522f333
    src_dir: "{{ qcow_image_local_source_dir | default('/home/iso') }}"
    rhsm_release: 8.2

__template_vm_details: []  # Only used for reporting - should be left empty
