---
- hosts: proxmox_host
  gather_facts: no
  module_defaults:
    proxmox_kvm:
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      api_host: "{{ groups['proxmox_host'][0] }}"
      node: "{{ groups['proxmox_host'][0] }}"
  tasks:
  - name: Add VMs to inventory
    include_role:
      name: proxmox-vms
      tasks_from: add_to_inventory.yml
  - name: Show ceph VM info
    debug:
      var: vm_details
  - pause:
      seconds: 10

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  - nfss
  - rbdmirrors
  - clients
  - iscsigws
  - iscsi-gws # for backward compatibility only!
  - mgrs
  - grafana-server
  become: yes
  tasks:
  - name: Prepare ceph VMs
    include_role:
      name: ceph
      tasks_from: prep.yml

- hosts: mons[0]
  become: no
  tasks:
  - name: Run ceph-ansible on first mon
    include_role:
      name: ceph
      tasks_from: run_ansible.yml

#- hosts: mons[0]
#  become: no
#  tasks:
#  - name: Run ceph-ansible (You can check ~/ansible/ansible.log for details)
#    shell: ansible-playbook -i hosts site.yml
#    args:
#      chdir: /usr/share/ceph-ansible
#    register: __ceph_ansible
#    async: 600
#    poll: 0
#  - name: Check on ceph-ansible task
#    async_status:
#      jid: "{{ __ceph_ansible.ansible_job_id }}"
#    until: job_result.finished
#    retries: 120
#    delay: 10
#    register: job_result
#  - name: Report ceph health
#    shell: ceph -s
#    become: yes
