---
- import_playbook: proxmox-ceph-add-to-inventory.yml

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  - nfss
  - rbdmirrors
  - clients
  - iscsigws
  - iscsi-gws # for backward compatibility only!
  - mgrs
  - grafana-server
  become: yes
  tasks:
  - name: Prepare ceph VMs
    include_role:
      name: ceph
      tasks_from: prep.yml

- hosts: mons[0]
  become: no
  tasks:
  - name: Run ceph-ansible on first mon
    include_role:
      name: ceph
      tasks_from: run_ansible.yml
