---
- hosts: proxmox_host
  module_defaults:
    proxmox_kvm:
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      api_host: "{{ groups['proxmox_host'][0] }}"
      node: "{{ groups['proxmox_host'][0] }}"
    prox_get_vm_configs:
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      api_host: "{{ groups['proxmox_host'][0] }}"
      node: "{{ groups['proxmox_host'][0] }}"
    prox_get_vm_status_by_name:
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      api_host: "{{ groups['proxmox_host'][0] }}"
      node: "{{ groups['proxmox_host'][0] }}"
  roles:
  - proxmox
  - proxmox-vms
