---
- import_playbook: proxmox-create-templates.yml
- import_playbook: proxmox-create-vms.yml

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  - nfss
  - rbdmirrors
  - clients
  - iscsigws
  - mgrs
  - grafana-server
  become: yes
  any_errors_fatal: yes
  tasks:
  - name: Prep ceph VMs
    include_role:
      name: ceph
      tasks_from: prep.yml

- hosts: mons[0]
  become: yes
  tasks:
  - name: Deploy ceph-ansible
    include_role:
      name: ceph
      tasks_from: prep_ansible.yml

- hosts: mons[0]
  become: no
  tasks:
  - name: Run ceph-ansible on first mon
    include_role:
      name: ceph
      tasks_from: run_ansible.yml
  - name: ceph-ansible post checks
    include_role:
      name: ceph
      tasks_from: post_checks.yml
