---
- hosts: proxmox_host
  module_defaults:
    proxmox_kvm:
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      api_host: "{{ groups['proxmox_host'][0] }}"
      node: "{{ groups['proxmox_host'][0] }}"
  tasks:
  - name: Remove ceph RHSM subscriptions
    include_role:
      name: ceph
      tasks_from: destroy.yml
  - name: Destroy ceph VMs
    include_role:
      name: proxmox-vms
      tasks_from: destroy.yml
