---
- hosts: proxmox_host
  roles:
  - proxmox-vms

- hosts: localhost
  tasks:
  - name: Create inventory file for ceph-ansible
    template:
      dest: ./ceph-ansible-inventory
      src: templates/ceph-ansible-inventory.j2

- hosts: mon,osd,mds
  gather_facts: no
  tasks:
  - name: Wait for SSH
    wait_for_connection:
      timeout: 60

- hosts: mon
  tasks:
  - ping:

- hosts: osd
  tasks:
  - ping:

- hosts: mds
  tasks:
  - ping:

- hosts: localhost
  tasks:
  - name: write_hostvars
    copy:
      dest: ./hostvars_all
      content: "{{ hostvars }}"
  - name: write_groups
    copy:
      dest: ./groups_all
      content: "{{ groups }}"
