---
- hosts: proxmox_host
  roles:
  - proxmox-vms

- hosts: localhost
  tasks:
  - name: Create inventory file for ceph-ansible
    template:
      dest: ./ceph-ansible-inventory
      src: templates/ceph-ansible-inventory.j2

- hosts: mons,osds,mdss
  gather_facts: no
  tasks:
  - name: Wait for SSH
    wait_for_connection:
      timeout: 60

- hosts: mons
  tasks:
  - ping:

- hosts: osds
  tasks:
  - ping:

- hosts: mdss
  tasks:
  - ping:
