---
- hosts: proxmox_host
  gather_facts: no
  module_defaults:
    proxmox_kvm:
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      api_host: "{{ groups['proxmox_host'][0] }}"
      node: "{{ groups['proxmox_host'][0] }}"
  tasks:
  - name: Add VMs to inventory
    include_role:
      name: proxmox-vms
      tasks_from: add_to_inventory.yml
  - name: Show ceph VM info
    debug:
      var: vm_details
  - pause:
      seconds: 10

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  - nfss
  - rbdmirrors
  - clients
  - iscsigws
  - iscsi-gws # for backward compatibility only!
  - mgrs
  - grafana-server
  become: yes
  tasks:
  - name: Prep ceph VMs
    include_role:
      name: ceph
      tasks_from: prep.yml

- hosts: mons[0]
  become: no
  tasks:
  - name: Post ceph-ansible checks
    include_role:
      name: ceph
      tasks_from: post_checks.yml
