---
- import_playbook: proxmox-ceph-add-to-inventory.yml

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  - nfss
  - rbdmirrors
  - clients
  - iscsigws
  - mgrs
  - grafana-server
  become: yes
  any_errors_fatal: no
  tasks:
  - include_role:
      name: ceph
      tasks_from: destroy.yml

- hosts: proxmox_host
  module_defaults:
    proxmox_kvm:
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      api_host: "{{ groups['proxmox_host'][0] }}"
      node: "{{ groups['proxmox_host'][0] }}"
  tasks:
  - include_role:
      name: proxmox-vms
      tasks_from: destroy.yml
