---
- hosts: proxmox_host
  roles:
  - proxmox-vms

- hosts: proxmox_host
  gather_facts: no
  tasks:
  - name: Show ceph VM info
    debug:
      var: vm_details
  - pause:
      seconds: 10

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  - nfss
  - rbdmirrors
  - clients
  - iscsigws
  - iscsi-gws # for backward compatibility only!
  - mgrs
  - grafana-server
  become: yes
  roles:
  - ceph-prep

- hosts: mons[0]
  become: yes
  tasks:
  - name: Deploy ceph-ansible
    include_role:
      name: ceph-prep
      tasks_from: ansible.yml
