---
- name: Destroy VM templates
  proxmox_kvm:
    name: "{{ item.key }}"
    state: absent
  loop: "{{ proxmox_templates | dict2items }}"
  register: __delete_status

- name: Show VM template delete status
  debug:
    msg: "{{ __delete_status.results | json_query('[].msg') }}"
