---
- name: Destroy VM templates
  proxmox_kvm:
    name: "{{ item.key }}"
    vmid: "{{ proxmox_template_starting_vmid + index }}"
    state: absent
  loop: "{{ proxmox_templates | dict2items }}"
  loop_control:
    index_var: index
  register: __delete_status

- name: Show delete status
  debug:
    msg: "{{ __delete_status.results | json_query('[].msg') }}"
