---
- name: Ensure qcow storage dir exists
  file:
    path: "{{ proxmox_template_qcow_storage_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Upload cloud images
  copy:
    src: "{{ item.value.src_dir }}/{{ item.value.image }}"
    dest: "{{ proxmox_template_qcow_storage_dir }}/{{ item.value.image }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ proxmox_templates | dict2items }}"

- name: Create template VMs
  proxmox_kvm:
    name: "{{ item.key }}"
    cores: "{{ item.value.cpu_count | default(default_vm_cpu_count) }}"
    memory: "{{ item.value.memory_mb | default(default_vm_memory_mb) }}"
    hotplug: network,disk,cpu,memory,usb
    onboot: "{{ item.value.onboot | default(default_vm_onboot) }}"
    vmid: "{{ proxmox_template_starting_vmid + index }}"
    net: '{"net0":"virtio,bridge={{ proxmox_network }}"}'
    agent: yes
  loop: "{{ proxmox_templates | dict2items }}"
  loop_control:
    index_var: index
  register: __prox_template_create

- name: Wait for template VMs creation
  proxmox_kvm:
    name: "{{ item.key }}"
    state: current
  loop: "{{ proxmox_templates | dict2items }}"
  loop_control:
    index_var: index
  retries: 10
  delay: 2
  until:
  - __prox_template_create_check is not failed
  - __prox_template_create_check.status == 'stopped'
  register: __prox_template_create_check

- name: Get snippet storage path
  shell: pvesh get /storage/vmstor-snippets --output-format json | jq -r '.path'
  changed_when: false
  register: __prox_snippet_path

- name: set snippet storage path fact
  set_fact:
    proxmox_snippet_path: "{{ __prox_snippet_path.stdout }}"

- name: Create template snippets
  template:
    src: cloud-init.cfg.j2
    dest: "{{ proxmox_snippet_path }}/snippets/{{ item.key }}-cloud-init.cfg"
    owner: root
    group: root
    mode: 0644
  loop: "{{ proxmox_templates | dict2items }}"
  loop_control:
    index_var: index

- name: Configure templates
  shell: |
    #!/bin/bash
    set -e
    qm importdisk {{ proxmox_template_starting_vmid + index }} {{ proxmox_template_qcow_storage_dir }}/{{ item.value.image }} {{ proxmox_storage }}
    qm set {{ proxmox_template_starting_vmid + index }} --scsihw virtio-scsi-pci --scsi0 {{ proxmox_storage }}:vm-{{ proxmox_template_starting_vmid + index }}-disk-0
    qm set {{ proxmox_template_starting_vmid + index }} --ide2 {{ proxmox_storage }}:cloudinit
    qm set {{ proxmox_template_starting_vmid + index }} --cicustom user={{ proxmox_storage_snippets }}:snippets/{{ item.key }}-cloud-init.cfg
    qm set {{ proxmox_template_starting_vmid + index }} --boot c --bootdisk scsi0
    qm set {{ proxmox_template_starting_vmid + index }} --numa 1
    qm template {{ proxmox_template_starting_vmid + index }}
  when: __prox_template_create.results[index] is changed
  async: 600
  poll: 0
  register: __prox_configure_templates
  loop: "{{ proxmox_templates | dict2items }}"
  loop_control:
    index_var: index

- name: Check on "Configure templates" task - this can take a while due to copying qcow images
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ __prox_configure_templates.results }}"
  loop_control:
    loop_var: async_result_item
    index_var: index
  register: __job_result
  when: __prox_configure_templates.results[index] is not skipped
  until: __job_result.finished
  retries: 60
  delay: 5
