---
- name: Report ceph health
  become: yes
  command: ceph -s -f json
  changed_when: false
  register: __ceph_health

- name: Show ceph health
  debug:
    msg: "{{ (__ceph_health.stdout | from_json).health }}"
