---
- name: Check ceph health
  become: yes
  shell: ceph -s -f json
  changed_when: false
  register: __ceph_health

- name: Get ceph health
  set_fact:
    ceph_health: "{{ (__ceph_health.stdout | from_json).health }}"

- name: Fail if ceph health is not WARN or OK)
  fail:
    msg: "Ceph health is bad: {{ ceph_health.status }}"
  when: ceph_health.status not in [ 'HEALTH_OK', 'HEALTH_WARN' ]

- name: Show ceph health
  debug:
    var: ceph_health

- name: Check grafana dashboard is working (unsupported on rhcs3)
  uri:
    url: "http://{{ hostvars[groups['mons'][0]].ansible_host }}:3000/api/org"
    user: admin
    password: "{{ ceph_grafana_admin_password }}"
    status_code: 200
  retries: 10
  delay: 5
  register: __check_grafana_dash
  until: __check_grafana_dash is not failed
  when: ceph_release != 'rhcs3'

- name: Check ceph dashboard is working (unsupported on rhcs3)
  uri:
    url: "http://{{ hostvars[groups['mons'][0]].ansible_host }}:8443"
    follow_redirects: all
    user: admin
    password: "{{ ceph_dashboard_admin_password }}"
    force_basic_auth: yes
    status_code: 200
  retries: 10
  delay: 5
  register: __check_ceph_dash
  until: __check_ceph_dash is not failed
  when: ceph_release != 'rhcs3'
