---
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Register system with rhsm
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    auto_attach: true
  register: __rhsm_register
  retries: 3
  delay: 1
  until: __rhsm_register is not failed

# Declaring the repositories in a comma-separated string is much faster than a loop with a list
- name: Enable rhsm repositories
  rhsm_repository:
    name: "{{ (ceph_repos[ceph_release | default(default_ceph_release)][ansible_distribution_major_version]) | join(',') }}"

# We install the ceph-common package so it's easy to run "ceph -s" etc commands on the ceph nodes without having
# to docker/podman exec
- name: Install ceph-common package
  package:
    name: ceph-common
    state: present

- name: Update packages
  yum:
    name: "*"
    state: latest

- name: Check if reboot is required
  shell: needs-restarting -r
  failed_when: false
  changed_when: false
  register: __reboot_required

- name: Reboot if required
  reboot:
    reboot_timeout: 3600
  when: __reboot_required.rc != 0
