---
- name: Set fact for cluster name
  set_fact:
    __ceph_cluster_name: "{{ ceph_cluster_name | default(default_ceph_cluster_name) }}"

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}.{{ __ceph_cluster_name }}"

- name: Add Ansible inventory mappings to /etc/hosts
  become: yes
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in (groups['all'] | sort) if host != groups['proxmox_host'][0] %}
      {{ hostvars[host].ansible_host }} {{ host }}.{{ __ceph_cluster_name }} {{ host }}
      {% endfor %}

- name: Set timezone
  timezone:
    name: "{{ vm_timezone | default(default_vm_timezone) }}"

- name: Register system with rhsm
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    pool_ids: "{{ rhsm_pool_id }}"
    #auto_attach: true
  register: __rhsm_register
  retries: 10
  delay: 1
  until: __rhsm_register is not failed
  tags:
  - rhsm

# Declaring the repositories in a comma-separated string is much faster than a loop with a list
- name: Enable rhsm repositories
  rhsm_repository:
    name: "{{ (ceph_repos[ceph_release | default(default_ceph_release)][ansible_distribution_major_version]) | join(',') }}"
  register: __rhsm_repos
  retries: 10
  delay: 1
  until: __rhsm_repos is not failed
  tags:
  - rhsm

- name: Apply any yum.conf package excludes
  ini_file:
    path: /etc/yum.conf
    section: main
    option: exclude
    value: "{{ yum_conf_excludes | join(',') }}"
    state: present
  when: yum_conf_excludes | bool

# We install the ceph-common package so it's easy to run "ceph -s" etc commands on the ceph nodes without having
# to docker/podman exec
- name: Install ceph-common package
  package:
    name: ceph-common
    state: present

- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: make sure line 'dns=dnsmasq' is set in /etc/NetworkManager/conf.d/999-dnsmasq.conf
  ini_file:
    path: /etc/NetworkManager/conf.d/999-dnsmasq.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: dnsmasq
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload NetworkManager

- name: Create dnsmasq config to use /etc/hosts file
  copy:
    dest: /etc/NetworkManager/dnsmasq.d/hosts.conf
    content: "addn-hosts=/etc/hosts"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload NetworkManager

- name: Update packages
  yum:  # noqa 403
    name: "*"
    state: latest
  tags:
  - yum-update

- name: Check if reboot is required
  command: needs-restarting -r
  failed_when: false
  changed_when: false
  register: __reboot_required

- name: Reboot if required
  reboot:
    reboot_timeout: 3600
  when: __reboot_required.rc != 0
