---
# This is only to be used on rhcs3 as the ceph metrics are included in ceph-ansible in >rhcs3
- name: Install cephmetrics-ansible package
  package:
    name: cephmetrics-ansible
    state: present
  become: yes

- name: Modify ansible.cfg
  ini_file:
    path: /usr/share/cephmetrics-ansible/ansible.cfg
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ cephmetrics_ansible_cfg_changes }}"
  become: yes

- name: Seed group_vars/all.yml file from sample file
  copy:
    src: /usr/share/cephmetrics-ansible/group_vars/all.yml.sample
    dest: /usr/share/cephmetrics-ansible/group_vars/all.yml
    remote_src: yes
    force: no
  become: yes

- name: Modify group_vars files
  become: yes
  lineinfile:
    path: "/usr/share/cephmetrics-ansible/group_vars/{{ item.0.name }}"
    regexp: "{{ item.1.regexp }}"
    line: "{{ item.1.line }}"
    state: present
  loop: "{{ cephmetrics_ansible_group_vars_changes | subelements('changes') }}"

- name: Run cephmetrics-ansible (You can check ~/ansible/ansible.log for details)
  shell: ansible-playbook -i /usr/share/ceph-ansible/hosts playbook.yml
  args:
    chdir: /usr/share/cephmetrics-ansible
  register: __cephmetrics_ansible
  ignore_errors: true
  async: 3600
  poll: 0

- name: Check on cephmetrics-ansible task (this task may take a very long time to complete)
  async_status:
    jid: "{{ __cephmetrics_ansible.ansible_job_id }}"
  until: __job_result.finished
  retries: 600
  delay: 10
  ignore_errors: true
  register: __job_result

- name: Show cephmetrics-ansible output
  debug:
    var: __job_result
