---
- name: "Run ceph-ansible (You can check /home/{{ ansible_ssh_user }}/ansible/ansible.log for details)"
  shell: ansible-playbook -i hosts site.yml
  args:
    chdir: /usr/share/ceph-ansible
  register: __ceph_ansible
  ignore_errors: true
  async: 1200
  poll: 0

- name: Check on ceph-ansible task (this task may take a very long time to complete)
  async_status:
    jid: "{{ __ceph_ansible.ansible_job_id }}"
  until: __job_result.finished
  retries: 120
  delay: 10
  ignore_errors: true
  register: __job_result

- name: dbg
  debug:
    var: __job_result

- name: Show last 20 lines of ceph-ansible output
  debug:
    msg: "{{ item }}"
    loop: "{{ __job_result.stdout_lines[-20:] }}"

- name: Report ceph health
  shell: ceph -s -f json
  register: __ceph_health
  become: yes

- name: Show ceph health
  debug:
    msg: "{{ (__ceph_health.stdout | from_json).health }}"
