---
- name: Run ceph-ansible (You can check ~/ansible/ansible.log for details)
  shell: ansible-playbook -i hosts site.yml
  args:
    chdir: /usr/share/ceph-ansible
  register: __ceph_ansible
  ignore_errors: true
  async: 3600
  poll: 0

- name: Check on ceph-ansible task (this task may take a very long time to complete)
  async_status:
    jid: "{{ __ceph_ansible.ansible_job_id }}"
  until: __job_result.finished
  retries: 600
  delay: 10
  ignore_errors: true
  register: __job_result

- name: Show ceph-ansible output
  debug:
    var: __job_result

- name: Include cephmetrics
  import_tasks: rhcs3_metrics.yml
  when: ceph_release == 'rhcs3'

- name: Report ceph health
  shell: ceph -s -f json
  register: __ceph_health
  become: yes

- name: Show ceph health
  debug:
    msg: "{{ (__ceph_health.stdout | from_json).health }}"
