---
- name: Run ceph-ansible (You can check ~/ansible/ansible.log for details)
  command: ansible-playbook -i hosts site.yml
  args:
    chdir: /usr/share/ceph-ansible
  register: __ceph_ansible
  ignore_errors: true
  #changed_when: __ceph_ansible.rc != 0
  async: 3600
  poll: 0

- name: Check on ceph-ansible task (this task may take a very long time to complete)
  async_status:
    jid: "{{ __ceph_ansible.ansible_job_id }}"
  until: __job_result.finished
  retries: 200
  delay: 30
  ignore_errors: true
  register: __job_result

- name: Show ceph-ansible output
  debug:
    var: __job_result

- name: Fail if ceph-ansible fails
  fail:
    msg: "ceph-ansible failed - check the ansible log"
  when: __job_result is failed

- name: Include cephmetrics
  import_tasks: ceph_metrics.yml
  when: ceph_release in [ 'rhcs2', 'rhcs3' ]

- name: Report ceph health
  command: ceph -s -f json
  changed_when: false
  register: __ceph_health
  become: yes

- name: Show ceph health
  debug:
    msg: "{{ (__ceph_health.stdout | from_json).health }}"
