---
- name: Run ceph-ansible (You can check ~/ansible/ansible.log for details)
  shell: ansible-playbook -i hosts site.yml
  args:
    chdir: /usr/share/ceph-ansible
  register: __ceph_ansible
  failed_when: false
  async: 1200
  poll: 0

- name: Check on ceph-ansible task (this task may take a very long time to complete)
  async_status:
    jid: "{{ __ceph_ansible.ansible_job_id }}"
  until: __job_result.finished
  retries: 120
  delay: 10
  register: __job_result

- name: Show ceph-ansible output
  debug:
    msg: "{{ item }}"
  loop: "{{ __ceph_ansible.stdout.lines }}"

- name: Report ceph health
  shell: ceph -s
  register: __ceph_health
  become: yes

- name: Show ceph health
  debug:
    var: "{{ __ceph_health.stdout }}"
