---
- name: Get eth0 network info from VMs (wait until eth0 is up)
  prox_get_vm_ip:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ groups['proxmox_host'][0] }}"
    node: "{{ groups['proxmox_host'][0] }}"
    vm_id: "{{ proxmox_vm_starting_vmid + index }}"
    vm_interface: eth0
  changed_when: false
  retries: 20
  delay: 2
  register: __vm_net
  until:
  - __vm_net is not failed
  - __vm_net.ip
  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
  loop_control:
    index_var: index

- name: Set vm_ips fact
  set_fact:
    vm_ips: "{{ __vm_net.results | json_query('[].ip') }}"

# REF: https://www.jeffgeerling.com/blog/2017/adding-strings-array-ansible to work out how to append to a list
- name: Append VMs to vm_details var
  set_fact:
    vm_details: "{{ vm_details }} + [ '{{ vm_name_prefix }}{{ item.key }} - {{ vm_ips[index] }}' ]"
  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
  loop_control:
    index_var: index

- name: Add ceph VMs to inventory
  add_host:
    name: "{{ vm_name_prefix }}{{ item.key }}"
    groups: "{{ item.value.groups }}"
    ansible_host: "{{ vm_ips[index] }}"
    ansible_user: "{{ item.value.ssh_user | default(default_vm_ssh_user) }}"
  changed_when: false
  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
  loop_control:
    index_var: index

- name: Show VM info
  debug:
    var: vm_details
- pause:
    seconds: 5
