---
- name: Stop running VMs
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ groups['proxmox_host'][0] }}"
    node: "{{ groups['proxmox_host'][0] }}"
    vmid: "{{ proxmox_vm_starting_vmid + index }}"
    name: "{{ item.key }}"
    state: stopped
  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
  loop_control:
    index_var: index

- name: delete VM
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ groups['proxmox_host'][0] }}"
    node: "{{ groups['proxmox_host'][0] }}"
    vmid: "{{ proxmox_vm_starting_vmid + index }}"
    name: "{{ item.key }}"
    state: absent
  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
  loop_control:
    index_var: index
  register: __delete_status

- name: Show delete status
  debug:
    msg: "{{ __delete_status.results | json_query('[].msg') }}"
