---
- name: Stop running VMs
  include_tasks: shutdown.yml

- name: delete VM
  proxmox_kvm:
    name: "{{ vm_name_prefix }}{{ item.key }}"
    state: absent
    timeout: 600
  loop: "{{ vm_scenarios[__vm_scenario] | dict2items }}"
  register: __delete_status

- name: Show delete status
  debug:
    msg: "{{ __delete_status.results | json_query('[].msg') }}"
