---
# TODO: We should rewrite this so it can handle creating VMs in parallel
- name: Create VMs
  include_tasks: create.yml
  vars:
    proxmox_host: "{{ groups['proxmox_host'][0] }}"
    vm_name: "{{ item.key }}"
    vm_id: "{{ proxmox_vm_starting_vmid + index }}"
    vm_network: "{{ item.value.network | default(proxmox_network) }}"
    vm_template: "{{ item.value.template }}"
    vm_storage: "{{ item.value.storage | default(proxmox_storage) }}"
    cpu_count: "{{ item.value.cpu_count | default(vm_cpu_count) | default(default_vm_cpu_count) }}"
    memory_mb: "{{ item.value.memory_mb | default(vm_memory_mb) | default(default_vm_memory_mb) }}"
    vm_disks: "{{ item.value.disks | default({}) }}"
  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
  loop_control:
    index_var: index

# TODO: We should rewrite this so it can handle starting VMs in parallel
- name: Start VMs
  include_tasks: start.yml
#  vars:
#    vm_name: "{{ item.key }}"
#    vm_id: "{{ proxmox_vm_starting_vmid + index }}"
#    vm_groups: "{{ item.value.groups }}"
#    vm_ssh_user: "{{ item.value.ssh_user | default(default_vm_ssh_user) }}"
#  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
#  loop_control:
#    index_var: index

- name: Add VMs to inventory
  include_tasks: add_to_inventory.yml
