---
- name: Create VMs
  include_tasks: create.yml
  vars:
    proxmox_host: "{{ groups['proxmox_host'][0] }}"
    vm_network: "{{ item.value.network | default(proxmox_network) }}"
    vm_template: "{{ item.value.template | default(default_vm_template) }}"
    vm_storage: "{{ item.value.storage | default(proxmox_storage) }}"
    cpu_count: "{{ item.value.cpu_count | default(vm_cpu_count) | default(default_vm_cpu_count) }}"
    memory_mb: "{{ item.value.memory_mb | default(vm_memory_mb) | default(default_vm_memory_mb) }}"
    vm_disks: "{{ item.value.disks | default({}) }}"

- name: Start VMs
  include_tasks: start.yml

- name: Add VMs to inventory
  include_tasks: add_to_inventory.yml
