---
- name: Stop running VMs
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ groups['proxmox_host'][0] }}"
    node: "{{ groups['proxmox_host'][0] }}"
    vmid: "{{ proxmox_vm_starting_vmid + index }}"
    name: "{{ item.key }}"
    state: stopped
  ignore_errors: yes
  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
  loop_control:
    index_var: index

- name: Poll VM status
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ groups['proxmox_host'][0] }}"
    node: "{{ groups['proxmox_host'][0] }}"
    vmid: "{{ proxmox_vm_starting_vmid + index }}"
    name: "{{ item.key }}"
    state: current
  register: __prox_shutdown_status
  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
  loop_control:
    index_var: index
  retries: 30
  delay: 2
  until: '__prox_shutdown_status.msg == "VM " ~ item.key ~ " with vmid = " ~ (proxmox_vm_starting_vmid+index) ~ " is stopped"'

- name: Show shutdown status
  debug:
    msg: "{{ __prox_shutdown_status.results | json_query('[].msg') }}"
