---
- name: Get VM config
  prox_get_vm_configs:
  register: __prox_vm_configs

- name: Stop running VMs
  proxmox_kvm:
    name: "{{ vm_name_prefix }}{{ item.key }}"
    state: stopped
    force: yes
  ignore_errors: yes
  async: 600
  poll: 0
  register: __prox_shutdown_vms
  loop: "{{ vm_scenarios[__vm_scenario] | dict2items }}"

- name: Check on "Stop running VMs" task
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ __prox_shutdown_vms.results }}"
  loop_control:
    loop_var: async_result_item
  register: __job_result
  until: __job_result.finished
  retries: 60
  delay: 5

- name: Wait until VMs are stopped
  proxmox_kvm:
    name: "{{ vm_name_prefix }}{{ item.key }}"
    state: current
  register: __prox_shutdown_status
  loop: "{{ vm_scenarios[__vm_scenario] | dict2items }}"
  retries: 30
  delay: 2
  until: '__prox_shutdown_status.msg == "VM " ~ vm_name_prefix ~ item.key ~ " with vmid = " ~ __prox_vm_configs.vm[vm_name_prefix ~ item.key].vmid ~ " is stopped"'  # noqa 204

- name: Show shutdown status
  debug:
    msg: "{{ __prox_shutdown_status.results | json_query('[].msg') }}"
