---
- name: Ensure VMs are started
  proxmox_kvm:
    vmid: "{{ proxmox_vm_starting_vmid + index }}"
    state: started
  loop: "{{ vm_scenarios[vm_scenario] | dict2items }}"
  loop_control:
    index_var: index
